version: '3'

services:

  app:
    image: chembience/sandbox-rdkit:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_sandbox_rdkit
    volumes:
      - "${RDKIT_APP_HOME}:/home/app"
      - "${CHEMBIENCE_SPHERE}:/home/sphere"
      - "${CHEMBIENCE_SHARE}:/share"
      - "~/data:/data"
    networks:
      - sphere
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - CHEMBIENCE_DB_USER
      - CHEMBIENCE_DB_HOST
      - CHEMBIENCE_DB_PORT
      - CHEMBIENCE_DB_PASSWORD=${CHEMBIENCE_DB_PASSWORD}
    depends_on:
      - db
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["python"]


  db:
    image: chembience/db:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_db
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - DEBUG=false
      - CHEMBIENCE_BUILD_LABEL
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - DB_USER=${CHEMBIENCE_DB_USER}
      - DB_PASS=${CHEMBIENCE_DB_PASSWORD}
      - DB_NAME=${CHEMBIENCE_DB_USER}
      - DB_TEMPLATE=
      - DB_EXTENSION=rdkit
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=


  job-management:
    image: rabbitmq:3-management
    container_name: job-management
    ports:
      - "15672:15672"
    networks:
      - sphere
    volumes:
      - job_management:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Rabbitmq0


volumes:
  db_volume:
  job_management:

networks:
  sphere:
